allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
minimumReleaseAgeExclude:
  - "@astrojs/markdown-satteri@0.3.1"
  - astro@7.0.0
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4
  - yaml@2.8.3
  - tar@7.5.16
overrides:
  tar@<7.5.7: ^7.5.7
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.15: ^7.5.16
  tar@<=7.5.2: ^7.5.3
  tar@<=7.5.3: ^7.5.4
  tar@<=7.5.9: ^7.5.10
  yaml@>=2.0.0 <2.8.3: ^2.8.3
