name: Nginx Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deployment
    runs-on: self-hosted

    steps:
      - name: Checkout tale/website
        uses: actions/checkout@v2

